### ISSUE TITLE
Content Readability

### ISSUE THREAD

**Issue by sheeceb** [UdaanSTC/GutsAndGlory#16]
I am finding it hard to change the column width and conserve niceness on github.

I have to move my head from left to right when reading the content and not enjoying it.

Will it be alright if I try experimenting with wordpress? I know you were saying that javascript doesn't work there. What's the most difficult piece or pieces content and presentation wise? I will see if it can be achieved.

These are just experiments for now.

Ani's reply

Problem is, even CSS doesn't work in Wordpress. Last time I checked, free Wordpress did not allow you to use CSS. That means, our entire presentation style goes for a toss.

If you just want the content to be confined to the middle one-thir of the screen, that can be achieved even in GitHub. Can you show me (a quick sketch) of whjat exactly you want?

Waise, the wisdom at N&N group is that content "above the fold" is what's read, and if we leave space on both sides of the screen, it just means we decrease the content "above the fold".

**Comment by sheeceb** [comment]
sorry for the bold text above. no idea how i did that.

This particular page if you notice is nice. The pupils of my eyes don't have to move.
Not sure what N&N is but with the current layout on my laptop I am resisting even going to the third line. I manually adjust the browser window to resize the page and read.

**Comment by AninditaBasu** [comment]
:) Bold is when you enclose something with two **. Look at the top right of the comment box. You see "M+ Markdown supported". Clicking that will lead you to a page that lists the formatting tags in Markdown. 

N & N is Norman & Nielsen, the usability people who're considered the last word (kind of) in UX. They're the ones who send out that "Alertbox" newsletter. This is the article I was referring to: [http://www.nngroup.com/articles/page-fold-manifesto/](http://www.nngroup.com/articles/page-fold-manifesto/). Also have a look at [http://www.nngroup.com/articles/screen-resolution-and-page-layout/](http://www.nngroup.com/articles/screen-resolution-and-page-layout/).

So, what you're saying is you want white space at the left and right of the screen. Can be done here as well. All I need to do is tweak the CSS files. (Wordpress doesn't give me as much flexibility with CSS and JS files). Do experiment with Wordpress: the most difficult pieces here are Anagha's and Prajakta's articles, and slightly less difficult is the Udaan home page and the Quiz page. The most straightforward page is Vinish's. See if they work well on Wordpress.

However, I'd like to hear others views too on the issue of white space at the left and right of the screen. I am being completely subjective but I don't find reading the text problematic at all. I wonder if that's because I keep the laptop at an arm's length (and never ever on my lap) so the entire screen is visible to me simultaneously.

**Comment by AninditaBasu** [comment]
Okay, looks like the bold text is not because of **. It looks like a heading (has an underline), so must be because you used the # symbol.

**Comment by sheeceb** [comment]
there were multiple dashes to separate your reply that's what made it bold.
