### ISSUE TITLE
No Passengers on the Battleship

### ISSUE THREAD

**Issue by jammingmarley** [UdaanSTC/GutsAndGlory#17]
My problem is that the Draft version of my article is up on the site, not the final one. Will be much easier for you to identify the changes  tracked in a Word doc, so will mail it to your id. Hope that's okay. Thanks!
Asha

**Comment by AninditaBasu** [comment]
@jammingmarley 
Hi Asha,
Have a look now, please. All okay?

**Comment by jammingmarley** [comment]
Thanks, Anindita!! Two corrections, please:

Could we use the image I sent? Please see attached here. The image currently used gives the wrong impression because it shows violence and murder. :) :)   Could we remove that? This one is from the free pixabay images collection - https://pixabay.com/en/photos/warship/

![warships-1017_640](https://cloud.githubusercontent.com/assets/14266532/9931955/b0d80246-5d5d-11e5-9a82-c7fe579e8c42.jpg)

Secondly, could we use "may" instead of "might" in this sentence? "Of course they might hate you in the short term." In the Sense of Urgency section.

Thanks once again for all your efforts!
Asha

**Comment by AninditaBasu** [comment]
@jammingmarley 
Both changes done and committed to the repo. If everything looks okay now, do close this issue.
Oh, and just because we're closing this issue doesn't mean you can't suggest any more changes :smile: You can, till about the end of this month.
And, if you have a few spare minutes, may I request you to scan some of the other articles as well? Peer review is always a great thing.

**Comment by jammingmarley** [comment]
Thanks so much! Will try to read the others too, after I am done with some more office work. :)
